version: "3.8"

services:
  web:
    build: .
    container_name: absen_web
    ports:
      - "8688:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: absen_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_absen
      MYSQL_USER: absen
      MYSQL_PASSWORD: absen123
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
